baseURL = "https://chungman.kim"
googleAnalytics = "UA-157392301-1"
languageCode = "en-us"
theme = "ananke"
title = "chungman.kim"
[params]
assets = "https://assets.chungman.kim"
author = "chungman kim"
background_color_class = "bg-black"
description = "chungman.kim"
facebook = ""
favicon = ""
featured_image = "/images/hero.jpg"
github = "https://github.com/choongmanee"
gitlab = ""
instagram = ""
linkedin = "https://www.linkedin.com/in/chungmankim"
mastodon = ""
show_reading_time = true
slack = ""
stackoverflow = ""
twitter = ""
youtube = ""
[permalinks]
posts = "/:year/:month/:title/"
