baseURL = "https://chungman.kim"
googleAnalytics = "UA-157392301-1"
languageCode = "en-us"
theme = "minimal-bootstrap-hugo-theme"
title = "chungman.kim"
[params]
assets = "https://assets.chungman.kim"
author = "chungman kim"
background_color_class = "bg-black"
facebook = ""
favicon = ""
featured_image = "/images/hero.jpg"
github = "https://github.com/choongmanee"
gitlab = ""
instagram = ""
linkedin = "https://www.linkedin.com/in/chungmankim"
mastodon = ""
show_reading_time = true
slack = ""
stackoverflow = ""
twitter = ""
youtube = ""
description = "Chungman.kim - Software engineer developing with Go, React, Flutter, and AWS"
contentBackgroundColor = "#fff"
contentTextColor = "#212529"
contentLinkColor = "#007bff"
contentLinkHoverColor = "#0056b3"
navbarBackgroundColor = "#212529"
navbarLinkColor = "rgba(255, 255, 255, 0.75)"
navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
wrapperMaxWidth = "800px"
customDateFormat = "Jan 2, 2006"
customCodeStyle = true
customBlockquoteStyle = true
showPostSummary = false
googleAnalytics = "UA-157392301-1"
cookieConsent = true
includeBootstrapJs = false
faviconSafariPinnedTabColor = "#5bbad5"
faviconMsApplicationTileColor = "#da532c"
faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 2
#  [[menu.nav]]
#  name = "About"
#  url = "/about/"
#  weight = 3
#  [[menu.nav]]
#  name = "RSS"
#  url = "/index.xml"
#  weight = 4

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2

[permalinks]
blog = "/:year/:month/:title/"

[taxonomies]
  tag = "tags"