title = "blog.chungman.kim"
baseURL = "https://blog.chungman.kim"
languageCode = "en-us"
googleAnalytics = "UA-157392301-1"
theme = "ananke"

[permalinks]
  posts = "/:year/:month/:title/"

[params]
  favicon = ""
  description = "blog.chungman.kim"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2